# Generated by Django 5.2.4 on 2025-07-25 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VictimSurvivorInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(blank=True, max_length=100, null=True)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('birthDate', models.DateField()),
                ('placeOfBirth', models.CharField(max_length=100)),
                ('civilStatus', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('SEPARATED', 'Separated'), ('DIVORCED', 'Divorced')], default='SINGLE', max_length=50)),
                ('ethnicity', models.CharField(blank=True, max_length=50, null=True)),
                ('mainOccupation', models.CharField(blank=True, max_length=100, null=True)),
                ('monthlyIncome', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('isDisplaced', models.BooleanField(default=False)),
                ('contactNumber', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('incidentDate', models.DateField()),
                ('incidentTime', models.TimeField()),
                ('incidentLocation', models.CharField(max_length=255)),
                ('victimSurvivor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk_officer.victimsurvivorinformation')),
            ],
        ),
        migrations.CreateModel(
            name='AllegedPerpetratorInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('birthdate', models.DateField()),
                ('birthPlace', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('mainOccupation', models.CharField(blank=True, max_length=100, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('victimSurvivor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk_officer.victimsurvivorinformation')),
            ],
        ),
    ]
