# Generated by Django 5.2.4 on 2025-07-29 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk_officer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='victimsurvivorinformation',
            old_name='birthDate',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='victimsurvivorinformation',
            old_name='placeOfBirth',
            new_name='birth_place',
        ),
        migrations.RenameField(
            model_name='victimsurvivorinformation',
            old_name='isSOGIE',
            new_name='is_SOGIE',
        ),
    ]
