# Generated by Django 5.2.4 on 2025-07-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_officer', '0002_rename_birthdate_victimsurvivorinformation_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='victimsurvivorinformation',
            name='civilStatus',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('SEPARATED', 'Separated'), ('DIVORCED', 'Divorced')], default='SINGLE', max_length=50),
        ),
    ]
