# Generated by Django 5.2.4 on 2025-07-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_officer', '0003_victimsurvivorinformation_civilstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='victimsurvivorinformation',
            old_name='civilStatus',
            new_name='civil_status',
        ),
        migrations.AddField(
            model_name='victimsurvivorinformation',
            name='PWD_type',
            field=models.CharField(choices=[('None', 'None'), ('Deaf or Hard of Hearing', 'Deaf or Hard of Hearing'), ('Intellectual Disability', 'Intellectual Disability'), ('Learning DIsability', 'Learning DIsability'), ('Mental Disability', 'Menatl Disability'), ('Orthopedic Disability', 'Orthopedic Disability'), ('Physical Disability', 'Physical Disability'), ('Psychological Disability', 'Psychological Disability'), ('Speech and Language Disability', 'Speech and Language Disability'), ('Visual Disability', 'Visual Disability')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='victimsurvivorinformation',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='victimsurvivorinformation',
            name='educational_attainment',
            field=models.CharField(choices=[('No Formal Education', 'No Formal Education'), ('Elementary Level/Graduate', 'Elementary Level/Graduate'), ('Junior High School Level/Graduate', 'Junior High School Level/Graduate'), ('Senior High School Level/Graduate', 'Senior High School Level/Graduate'), ('Technical/Vocational', 'Technical/Vocational'), ('College Level/Graduate', 'College Level/Graduate'), ('Post graduate', 'Post graduate')], default='No Formal Education', max_length=50),
        ),
        migrations.AddField(
            model_name='victimsurvivorinformation',
            name='employment_status',
            field=models.CharField(choices=[('Employed', 'Employed'), ('Self-employed', 'Self-employed'), ('Unemployed', 'Unemployed'), ('Informal Sector', 'Informal Sector'), ('Not Applicable', 'Not Applicable')], default='Not Applicable', max_length=50),
        ),
        migrations.AddField(
            model_name='victimsurvivorinformation',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='victimsurvivorinformation',
            name='is_displaced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='victimsurvivorinformation',
            name='main_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='victimsurvivorinformation',
            name='migratory_status',
            field=models.CharField(choices=[('Current OFW', 'Current OFW'), ('Former/Returning OFW', 'Former/Returning OFW'), ('Seeking employment abroad', 'Seeking employment abroad'), ('Not Applicable', 'Not Applicable')], default='Not Applicable', max_length=50),
        ),
        migrations.AddField(
            model_name='victimsurvivorinformation',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='victimsurvivorinformation',
            name='religion',
            field=models.CharField(choices=[('Roman Catholic', 'Roman Catholic'), ('Islam', 'Islam'), ('Evangelicals', 'Evangelicals'), ('Protestant', 'Protestant'), ('Iglesia ni Cristo', 'Iglesia ni Cristo'), ('Others', 'Others')], default='Roman Catholic', max_length=50),
        ),
    ]
